### PR TITLE
Ensure accessed indexes do exist

### PR DESCRIPTION
**Pull request by okaufmann**
Hi,

Another "problem" I noticed, is that the parts from a dig command output are accessed directly. Even if the count of attributes does not match the expected ones.

This PR fixes this, by checking the count of attributes before accessing them.

Hope this helps

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests for this?

**Comment by okaufmann** [comment]
I can, I should before, and I did now. Sorry, for forgetting to write them!

**Comment by okaufmann** [comment]
@freekmurze there will be a merge conflict. Let me know if you merged https://github.com/spatie/dns/pull/70 so I can fix them.

**Comment by freekmurze** [comment]
#70 has been merged

**Comment by okaufmann** [comment]
Great. Conflicts were resolved ✅

**Comment by freekmurze** [comment]
Is this enforcing needed? Would it be more flexible if that check doesn't happen (I'm thinking of maybe old tools that might not return all needed info)

**Comment by okaufmann** [comment]
My main concern was to prevent the warnings, when accessing a not existing array index due to the parsing (e.g. https://github.com/spatie/dns/blob/main/src/Records/MX.php#L18-L24) happens before the type check (https://github.com/spatie/dns/blob/main/src/Records/Record.php#L29) is done and handled (https://github.com/spatie/dns/blob/main/src/Handlers/Handler.php#L42).

This then results in a warning thrown:

image

I agree that this is a aggressive way to prevent warnings. So, I tried to allow missing indexes by using the null coalescing operator and therefore support not complete lines (for old tools as you stated) for a given record type:

image

But this does result (in this specific case) in an exception when using casting methods for properties anyway (Same happens if warnings are ignored by ignore in php config):

image

I'm not certain if it's not working properly anyway, if old tools return incomplete lines.

IMHO, there are two ways to handle this:
- Make sure the accessed attributes does exist and return null for incomplete records (what this PR wants to change).
- Allow Cast Methods to get "nullish" values and return a complete record with not all properties filled up.

For the second way, I quickly set up a draft that handles it way more loose and tries to keep as much information as it gets: https://github.com/spatie/dns/pull/71

Looking forward to your feedback.

**Comment by freekmurze** [comment]
Let's go for this approach, and we'll handle any edge cases by old tools as people report them. Thanks!

**Comment by okaufmann** [comment]
Thanks! Feel free to mention me in such cases so I can help fixing issues related to this change.

**Pull request merged**
