### PR TITLE
Refactor in order to extract DNS client

### PR DESCRIPTION
**Pull request by ptondereau**
Hello,

This PR aims to extract all code based on DNS client tools.
Indeed, Everybody doesn't have `dig` installed and I wanted to start building the foundation to get more client.

Doc is not here yet, because I'm waiting for approval first.

### CODE REVIEW

**Comment by freekmurze** [comment]
I'm thinking most people do have `dig` installed. Which other tools would you like to use to perform dns lookups and in what way are they better than `dig`?

**Comment by ptondereau** [comment]
There is core PHP function: http://php.net/manual/fr/function.dns-get-record.php
Windows use a tool called nslookup

**Comment by ptondereau** [comment]
This is not a question about which one is better than another one. It's about choice.

**Comment by freekmurze** [comment]
Thank you for your work but I'm not going to merge this in because I don't think it solves an actual problem for us atm.

If you want to use this, feel free to fork our code and maintain your own copy.

**Pull request closed without merging**
