### PR TITLE
fix lower dependency

### PR DESCRIPTION
**Pull request by TVke**

### CODE REVIEW

**Comment by freekmurze** [comment]
All tests seems to be failing now (see Travis), could you also allow Symfony 4?

**Comment by TVke** [comment]
The tests are not failing because of the Symfony dependency.
It fails because there is no `TXT` record any more on the [spatie.be](https://spatie.be) site.
I used this [tool](https://toolbox.googleapps.com/apps/dig/#TXT/) to be sure and it has an empty `ANSWER` body.

**Comment by freekmurze** [comment]
The dns records of spatie.be have indeed changed. Could you change the
tests so they work with the new values?





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by TVke** [comment]
zo dat is gefixt.

**Comment by freekmurze** [comment]
Could you also allow Symfony 4 (and PHPUnit 7 while you're at it)

**Comment by TVke** [comment]
Just upgraded

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
