### PR TITLE
Allow searching domains with foreign characters

### PR DESCRIPTION
**Pull request by crock**
Implemented first part of fix recommended here
https://github.com/spatie/dnsrecords.io/issues/39#issuecomment-368047216

### CODE REVIEW

**Comment by crock** [comment]
No need to merge this yet, I'll finish the rest so it can be in the same PR.

**Comment by freekmurze** [comment]
Ok, ping me when I should have a look.

Thanks for your work on this!

**Comment by crock** [comment]
@freekmurze Alright, I think it's ready. I have made sure all the test cases passed. You do need to install the `intl` extension for PHP 7.2 for it to work.

**Comment by crock** [comment]
Nvm, not ready yet

**Comment by manniL** [comment]
Any updates on it @crock? :relaxed:

**Comment by crock** [comment]
@manniL Even though it passes the tests, it still doesn't properly support emoji domain names and I don't know why.  I was stumped, so I just gave up hoping somebody else would be able to spot my mistake. I feel ashamed that I couldn't do it. 😔

**Comment by manniL** [comment]
@crock Don't worry :relaxed: 
Could you add failing tests for the emoji domains? :thinking: So it'd be easier to track down the problem.

**Comment by freekmurze** [comment]
Closing this due to inactivity. Feel free to open up a new PR.

**Pull request closed without merging**
