### PR TITLE
Fix Undefined constant DNS_CAA in windows platform

### PR DESCRIPTION
**Pull request by ManojKiranA**

### CODE REVIEW

**Comment by ManojKiranA** [comment]
It would be add windows os to github actions.

**Comment by freekmurze** [comment]
Seems like the tests are failing for this one.

**Comment by ManojKiranA** [comment]
will fix it ASAP

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
> It would be nice to add windows operating system to github actions.

Do all the tests pass when you run them on your local system?

**Pull request merged**
